# Generated by Django 4.2 on 2023-05-09 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
        migrations.AddField(
            model_name='product',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='release date'),
            preserve_default=False,
        ),
    ]
