# Generated by Django 4.2 on 2023-05-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this category should be treated as active. Unselect this instead of deleting categories.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_index',
            field=models.SmallIntegerField(default=0, verbose_name='sort index'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this product should be treated as active. Unselect this instead of deleting products.', verbose_name='active'),
        ),
    ]
