# Generated by Django 4.2 on 2023-05-14 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='depth',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='depth'),
        ),
    ]
