# Generated by Django 4.2 on 2023-05-23 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_review_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='specification',
            unique_together={('name', 'value')},
        ),
    ]
