# Generated by Django 4.2 on 2023-05-26 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='product'),
        ),
    ]
