version: "3.9"

services:
  app:
    build:
      context: .
#      dockerfile: ./Dockerfile
    container_name: app
    command:
      - "python"
      - "manage.py"
      - "runserver"
      - "0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: unless-stopped
#    environment:
#      - "DJANGO_DEBUG=1"  # temporally
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
#    volumes:
#      - ./bg_shop/database:/app/database
#    depends_on:
#      - rabbitmq
#      - worker
  rabbitmq:
    image: rabbitmq:management
    container_name: app-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  worker:
    build:
      context: .
    container_name: app-worker
    command: celery -A bg_shop worker -l info
    volumes:
      - ./bg_shop:/app
    network_mode: host
    depends_on:
      - rabbitmq