version: "3.9"

services:
  app:
    build:
      context: .
    container_name: app

    command: >
      bash -c "gunicorn --bind 0.0.0.0:8000 bg_shop.wsgi"
#    command: >
#      bash -c "python manage.py migrate
#      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    volumes:
      - ./bg_shop:/app/
      - ./config/:/config/
#      - ./bg_shop/database:/app/database
#      - ./bg_shop/media:/app/media
    depends_on:
      - rabbitmq
      - worker
      - db

  rabbitmq:
    image: rabbitmq:management
    container_name: app-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"

  worker:
    build:
      context: .
    container_name: app-worker
    command: celery -A bg_shop worker -l info
    volumes:
      - ./bg_shop:/app
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    depends_on:
      - rabbitmq

  db:
    image: postgres:15.3
    restart: always
#    volumes:
#      - ./bg_shop/database:/var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  nginx:
    image: nginx:1.24.0
    restart: always
    volumes:
      - ./config/nginx/:/etc/nginx/templates/
      - .:/code
    ports:
      - "80:80"

volumes:
  postgres_data: