# Generated by Django 4.2 on 2023-07-05 17:17

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='images', validators=[common.validators.FileMaxSizeValidator(limit_value=2097152, message='Max file size is 2048.0KB')], verbose_name='image'),
        ),
    ]
