# Generated by Django 4.2 on 2023-05-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(default='blank', upload_to='images', verbose_name='image'),
            preserve_default=False,
        ),
    ]
