# Generated by Django 4.2 on 2023-06-10 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicConfig',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('ordinary_delivery_cost', models.DecimalField(decimal_places=2, default=0, help_text='sets base cost of delivery', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ordinary delivery cost')),
                ('express_delivery_extra_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='express delivery extra charge')),
                ('boundary_of_free_delivery', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='boundary of free delivery')),
                ('company_info', models.TextField(blank=True, max_length=5120, null=True, verbose_name='company info')),
                ('legal_address', models.TextField(blank=True, max_length=1024, null=True, verbose_name='legal address')),
                ('main_phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='main phone')),
                ('main_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='main email')),
            ],
            options={
                'verbose_name': 'dynamic config',
                'verbose_name_plural': 'dynamic configs',
            },
        ),
    ]
