# Generated by Django 4.2 on 2023-05-18 16:59

from django.db import migrations


def forwards_func(apps, schema_editor):
    DynamicConfig = apps.get_model("dynamic_config", "DynamicConfig")
    db_alias = schema_editor.connection.alias
    d_config = DynamicConfig(  # todo get data from env
        id=1,
        regular_delivery_cost=200,
        express_delivery_extra_charge=500,
        boundary_of_free_delivery=200,
        company_info="lorem",
        legal_address="baker st. 221b",
        main_phone="+7(992)263-45-62",
        main_email="asd@dot.com",
    )
    d_config.save()


def reverse_func(apps, schema_editor):
    DynamicConfig = apps.get_model("dynamic_config", "DynamicConfig")
    db_alias = schema_editor.connection.alias
    DynamicConfig.objects.using(db_alias).filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_config', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
