# Generated by Django 4.2 on 2023-05-18 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicconfig',
            name='main_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='main email'),
        ),
        migrations.AlterField(
            model_name='dynamicconfig',
            name='regular_delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='sets base cost of delivery', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='regular delivery cost'),
        ),
    ]
