# Generated by Django 4.2 on 2023-06-10 14:27
from django.db import migrations
from django.conf import settings


def forwards_func(apps, schema_editor):
    DynamicConfig = apps.get_model("dynamic_config", "DynamicConfig")
    db_alias = schema_editor.connection.alias
    d_config = DynamicConfig(
        id=1,
        ordinary_delivery_cost=settings.ORDINARY_DELIVERY_COST,
        express_delivery_extra_charge=settings.EXPRESS_DELIVERY_EXTRA_CHARGE,
        boundary_of_free_delivery=settings.BOUNDARY_OF_FREE_DELIVERY,
        company_info=settings.COMPANY_INFO,
        legal_address=settings.LEGAL_ADDRESS,
        main_phone=settings.MAIN_PHONE,
        main_email=settings.MAIN_EMAIL,
    )
    d_config.save()


def reverse_func(apps, schema_editor):
    DynamicConfig = apps.get_model("dynamic_config", "DynamicConfig")
    db_alias = schema_editor.connection.alias
    DynamicConfig.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_config', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
