from shop.selectors.category_selectors import CategorySelector
from shop.selectors.product_selectors import ProductSelector
from shop.selectors.review_selelctors import ReviewSelector
from shop.selectors.banner_selectors import BannerSelector
from shop.selectors.sales_selectors import SaleSelector
