# Generated by Django 4.2 on 2023-05-09 14:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created at')),
                ('delivery_type', models.CharField(choices=[('RE', 'regular'), ('EX', 'express')], max_length=2, verbose_name='delivery type')),
                ('status', models.CharField(choices=[('ED', 'editing'), ('AC', 'accepted'), ('RJ', 'rejected'), ('CO', 'completed')], default='ED', max_length=2, verbose_name='status')),
                ('city', models.CharField(max_length=255, verbose_name='city')),
                ('address', models.TextField(max_length=1024, verbose_name='address')),
                ('comment', models.TextField(max_length=1024, verbose_name='comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='price')),
                ('count', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='count')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'ordered product',
                'verbose_name_plural': 'ordered products',
            },
        ),
    ]
