# Generated by Django 4.2 on 2023-05-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this order should be treated as active. Unselect this instead of deleting orders.', verbose_name='active'),
        ),
    ]
