# Generated by Django 4.2 on 2023-06-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('ON', 'online'), ('CA', 'cash'), ('SO', 'someone')], default='ON', max_length=2, verbose_name='payment_type'),
        ),
    ]
