# Generated by Django 4.2 on 2023-06-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_review_date'),
        ('orders', '0003_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderedproduct',
            unique_together={('product', 'order')},
        ),
    ]
