# Generated by Django 4.2 on 2023-06-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_address_alter_order_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CT', 'cart'), ('ED', 'editing'), ('AC', 'accepted'), ('RJ', 'rejected'), ('CO', 'completed')], default='ED', max_length=2, verbose_name='status'),
        ),
    ]
