# Generated by Django 4.2 on 2023-06-10 14:17

from django.db import migrations, models
import django.db.models.deletion
import payment.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8, validators=[payment.validators.PaymentNumberRegexValidator], verbose_name='number')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('validity_period', models.DateField(verbose_name='validity period')),
                ('code', models.IntegerField(verbose_name='code')),
                ('payment_type', models.CharField(choices=[('ON', 'online'), ('RN', 'random')], max_length=2, verbose_name='payment type')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
            },
        ),
    ]
