# Generated by Django 4.2 on 2023-06-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='code',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='validity_period',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='init', max_length=255, verbose_name='payment id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='service',
            field=models.CharField(choices=[('TE', 'test')], default='TE', max_length=2, verbose_name='service'),
        ),
    ]
