# Generated by Django 4.2 on 2023-05-09 15:52

from django.db import migrations, models
import payment.validators


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='number',
            field=models.CharField(max_length=8, validators=[payment.validators.PaymentNumberRegexValidator], verbose_name='number'),
        ),
    ]
