# Generated by Django 4.2 on 2023-05-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_paymenttype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('ON', 'online'), ('RN', 'random')], default='ON', max_length=2, verbose_name='payment type'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PaymentType',
        ),
    ]
